version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: openpg
      POSTGRES_PASSWORD: openpgpwd
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/AttndCtrl
    ports:
      - "3000:3000"
    depends_on:
      - db